---
# defaults file for apache2
dependencies:
  - curl

path_www: "/var/www/wescale.com/html"
path_site: "/etc/apache2/sites-available"
index_name: "index.html"
site_name: "wescale.com.conf"

title_message: "Welcome to Devoxx"
header_message: "Success ! YEAHHHHHHH NO DEMO EFFECT !!!!!"

template_list:
  - name: index.html.j2
    path: "{{ path_www }}/{{ index_name }}"
    title: "{{ title_message }}"
    header: "{{ header_message }}"

  - name: wescale.com.conf.j2
    path: "{{ path_site }}/{{ site_name }}"
    serveradmin: "admin@wescale.com"
    servername: "wescale.com"
    serveralias: "www.wescale.com"
    documentroot: "{{ path_www }}"
    errorlog: "/var/log/error.log"
    customlog: "/var/log/access.log combined"
 
port: 80
