---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install dependecies "{{ item }}"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dependencies }}"

- name: install apache2
  apt:
    name: apache2
    state: present
  notify: start apache2
  register: result

- name: flush handlers
  meta: flush_handlers

- name: Wait for apache2 is up
  wait_for:
    host: localhost
    port: "{{ port}}"
    delay: 10
    timeout: 100
  when: result.changed
