---
# handlers file for apache2
- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: stop apache2
  service:
    name: apache2
    state: stopped

- name: start apache2
  service:
    name: apache2
    state: started
